In [221]:
import numpy as np

from keras.models import Sequential
from keras.layers import Embedding
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf

In [222]:
##### Data in text format #####
# Read, then decode for py2 compat.
text = open('/Users/giovannafilipakis/Desktop/keras-projects/database', 'rb').read().decode(encoding='utf-8')

# length of text is the number of characters in it
print ('Length of text: {} characters'.format(len(text)))
print(text)

Length of text: 351 characters
Lista, Pilha, Fila, Lista Simplesmente Encadeada, Lista Duplamente Encadeada, Árvore, 9
Pilha, Fila, Lista, Lista Simplesmente Encadeada, Lista Duplamente Encadeada, Árvore, 6
Árvore, Pilha, Fila, Lista, Lista Simplesmente Encadeada, Lista Duplamente Encadeada, 5
Pilha, Lista, Lista Simplesmente Encadeada, Lista Duplamente Encadeada, Fila, Árvore, 6


In [223]:
##### Data in text format #####
#qtnd de caracteres 

vocab_t = sorted(set(text))
print(vocab_t)
print ('{} unique characters'.format(len(vocab_t)))

['\n', ' ', ',', '5', '6', '9', 'D', 'E', 'F', 'L', 'P', 'S', 'a', 'c', 'd', 'e', 'h', 'i', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'Á']
29 unique characters


In [224]:
##### Data in list format #####

data_set = ['Lista', 'Pilha', 'Fila', 'Lista Simplesmente Encadeada', 'Lista Duplamente Encadeada', 'Árvore', '9',
             'Pilha', 'Fila', 'Lista', 'Lista Simplesmente Encadeada', 'Lista Duplamente Encadeada', 'Árvore', '6',
             'Árvore', 'Pilha', 'Fila', 'Lista', 'Lista Simplesmente Encadeada', 'Lista Duplamente Encadeada', '5',
             'Pilha', 'Lista', 'Lista Simplesmente Encadeada', 'Lista Duplamente Encadeada', 'Fila', 'Árvore', '6']

In [225]:
##### Data in list format #####
#qtnd de caracteres 

vocab_l = sorted(set(data_set))
print(vocab_l)
print ('{} unique characters'.format(len(vocab_l)))

['5', '6', '9', 'Fila', 'Lista', 'Lista Duplamente Encadeada', 'Lista Simplesmente Encadeada', 'Pilha', 'Árvore']
9 unique characters


In [226]:
# Creating a mapping from unique characters to indices

char2idx = {u:i for i, u in enumerate(vocab_l)}
idx2char = np.array(vocab_l)

text_as_int = np.array([char2idx[c] for c in data_set])

print('{')
for char,_ in zip(char2idx, range(20)):
    print('  {:4s}: {:3d},'.format(repr(char), char2idx[char]))
print('  ...\n}')

{
  '5' :   0,
  '6' :   1,
  '9' :   2,
  'Fila':   3,
  'Lista':   4,
  'Lista Duplamente Encadeada':   5,
  'Lista Simplesmente Encadeada':   6,
  'Pilha':   7,
  'Árvore':   8,
  ...
}


In [227]:
#char2int das sequências

values = np.array(data_set)
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

['Lista' 'Pilha' 'Fila' 'Lista Simplesmente Encadeada'
 'Lista Duplamente Encadeada' 'Árvore' '9' 'Pilha' 'Fila' 'Lista'
 'Lista Simplesmente Encadeada' 'Lista Duplamente Encadeada' 'Árvore' '6'
 'Árvore' 'Pilha' 'Fila' 'Lista' 'Lista Simplesmente Encadeada'
 'Lista Duplamente Encadeada' '5' 'Pilha' 'Lista'
 'Lista Simplesmente Encadeada' 'Lista Duplamente Encadeada' 'Fila'
 'Árvore' '6']
[4 7 3 6 5 8 2 7 3 4 6 5 8 1 8 7 3 4 6 5 0 7 4 6 5 3 8 1]


In [228]:
#one-hot encoding das sequências

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [229]:
#reverter one-hot encoding das sequências

for i in onehot_encoded:
    inverted = label_encoder.inverse_transform([np.argmax(i)])
    print(inverted)

['Lista']
['Pilha']
['Fila']
['Lista Simplesmente Encadeada']
['Lista Duplamente Encadeada']
['Árvore']
['9']
['Pilha']
['Fila']
['Lista']
['Lista Simplesmente Encadeada']
['Lista Duplamente Encadeada']
['Árvore']
['6']
['Árvore']
['Pilha']
['Fila']
['Lista']
['Lista Simplesmente Encadeada']
['Lista Duplamente Encadeada']
['5']
['Pilha']
['Lista']
['Lista Simplesmente Encadeada']
['Lista Duplamente Encadeada']
['Fila']
['Árvore']
['6']


In [230]:
##### Create training examples and targets #####

# The maximum length sentence we want for a single input in characters
seq_length = 6
examples_per_epoch = len(data_set)#(seq_length+1)

char_dataset = tf.data.Dataset.from_tensor_slices(onehot_encoded)
# for i in char_dataset:
#     print(i)

sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

#print batches encoded
for i in sequences:
    print(i)
    
#print batches as text
for i in sequences:
    for j in i:
        print(''.join(label_encoder.inverse_transform([np.argmax(j)])))

# for item in sequences:
#   print(repr(''.join(label_encoder.inverse_transform([np.argmax(item)]))))

tf.Tensor(
[[0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(7, 9), dtype=float64)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]], shape=(7, 9), dtype=float64)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(7, 9), dtype=float64)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]], shape=(7, 9), dtype=f

In [231]:
##### Create training examples and targets #####

def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

#foreach item in sequences apply split_input_target
dataset = sequences.map(split_input_target)

#print input_text and target_text as text
for input_example, target_example in  dataset.take(1):
    for i in input_example:
        print(''.join(label_encoder.inverse_transform([np.argmax(i)])))
    print('\n')
    for i in target_example:
        print(''.join(label_encoder.inverse_transform([np.argmax(i)])))

Lista
Pilha
Fila
Lista Simplesmente Encadeada
Lista Duplamente Encadeada
Árvore


Pilha
Fila
Lista Simplesmente Encadeada
Lista Duplamente Encadeada
Árvore
9


In [232]:
for i, (input_idx, target_idx) in enumerate(zip(input_example, target_example)):
    print("Step {:4d}".format(i))
    print("  input: {} ({:s})".format(input_idx, str(label_encoder.inverse_transform([np.argmax(input_idx)]))))
    print("  expected output: {} ({:s})".format(target_idx, str(label_encoder.inverse_transform([np.argmax(target_idx)]))))

Step    0
  input: [0. 0. 0. 0. 1. 0. 0. 0. 0.] (['Lista'])
  expected output: [0. 0. 0. 0. 0. 0. 0. 1. 0.] (['Pilha'])
Step    1
  input: [0. 0. 0. 0. 0. 0. 0. 1. 0.] (['Pilha'])
  expected output: [0. 0. 0. 1. 0. 0. 0. 0. 0.] (['Fila'])
Step    2
  input: [0. 0. 0. 1. 0. 0. 0. 0. 0.] (['Fila'])
  expected output: [0. 0. 0. 0. 0. 0. 1. 0. 0.] (['Lista Simplesmente Encadeada'])
Step    3
  input: [0. 0. 0. 0. 0. 0. 1. 0. 0.] (['Lista Simplesmente Encadeada'])
  expected output: [0. 0. 0. 0. 0. 1. 0. 0. 0.] (['Lista Duplamente Encadeada'])
Step    4
  input: [0. 0. 0. 0. 0. 1. 0. 0. 0.] (['Lista Duplamente Encadeada'])
  expected output: [0. 0. 0. 0. 0. 0. 0. 0. 1.] (['Árvore'])
Step    5
  input: [0. 0. 0. 0. 0. 0. 0. 0. 1.] (['Árvore'])
  expected output: [0. 0. 1. 0. 0. 0. 0. 0. 0.] (['9'])


In [244]:
##### Create training batches #####

# Batch size
BATCH_SIZE = 4

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10

# print(dataset)
# for i in dataset:
#     print(i)

datasetBatch = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)
# If your program depends on the batches having the same outer dimension,
# you should set the drop_remainder argument to True to prevent the smaller
# batch from being produced.

print(datasetBatch)
for i in datasetBatch:
    print(i)

<BatchDataset shapes: ((4, 6, 9), (4, 6, 9)), types: (tf.float64, tf.float64)>
(<tf.Tensor: shape=(4, 6, 9), dtype=float64, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 0., 0.