In [2]:
import numpy as np

from keras.models import Sequential
from keras.layers import Embedding
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf
import os
import random
import re

In [3]:
#with open('C:/Users/Giovanna/Documents/TCC/keras-projects/conteudos.csv', encoding="utf8") as myfile:
#    conteudos = myfile.read().split('\n')

#def cria_seq_teste(conteudos):
#    data = conteudos[:]
#    random.shuffle(data)
#    value = random.randint(0, 10)
#    data.append(str(value))
#    return data
#    
#data_set = []
#for i in range(50):
#    seq = cria_seq_teste(conteudos)
#    for i in seq:
#        data_set.append(i)
#        
#print(data_set)

In [4]:
#nova base de dados

with open('C:/Users/Giovanna/Documents/TCC/keras-projects/dados-iniciais.csv', "r") as myfile:
    novos = myfile.read()
    data_set = re.split('\n|,',novos)[:-1]
print(data_set)

['Listas Dinâmicas Simplesmente Encadeadas Circulares', 'Listas Estáticas', 'Árvores Binárias', 'Listas Estáticas Circulares', 'Listas Estáticas Sequenciais', 'Listas Dinâmicas Duplamente Encadeadas', 'Filas de Prioridade', 'Pilhas', 'Listas Dinâmicas', 'Aplicações de Pilhas', 'Árvores Binárias de Busca', 'Pilhas Dinâmicas', 'Percursos em Árvores Binárias', 'Listas Dinâmicas Simplesmente Encadeadas', 'Árvores BInárias de Busca Balanceadas', 'Listas Dinâmicas Duplamente Encadeadas Circulares', 'Filas Estáticas', 'Aplicações de Filas', 'Pilhas Estáticas', 'Tipos Abstratos de Dados', 'Listas Estáticas Encadeadas', 'Recursividade', 'Listas', 'Filas Dinâmicas', 'Filas', 'Ruim', 'Listas Estáticas Sequenciais', 'Filas Dinâmicas', 'Pilhas', 'Listas Estáticas Circulares', 'Filas Estáticas', 'Listas Dinâmicas Duplamente Encadeadas', 'Aplicações de Filas', 'Árvores Binárias', 'Listas Estáticas Encadeadas', 'Listas Estáticas', 'Listas', 'Pilhas Estáticas', 'Tipos Abstratos de Dados', 'Recursividad

In [5]:
##### Data in list format #####


#Todas as sequências tem o mesmo comprimento
#Vetores de tamanho fixo
#data_set = ['Lista', 'Pilha', 'Fila', 'Lista Simplesmente Encadeada', 'Lista Duplamente Encadeada', 'Árvore', '9',
#             'Pilha', 'Fila', 'Lista', 'Lista Simplesmente Encadeada', 'Lista Duplamente Encadeada', 'Árvore', '6',
#             'Árvore', 'Pilha', 'Fila', 'Lista', 'Lista Simplesmente Encadeada', 'Lista Duplamente Encadeada', '5',
#             'Pilha', 'Lista', 'Lista Simplesmente Encadeada', 'Lista Duplamente Encadeada', 'Fila', 'Árvore', '6']

In [6]:
##### Data in list format #####

#itens distintos 
vocab_l = sorted(set(data_set))
print(vocab_l)
print ('{} itens distintos'.format(len(vocab_l)))

['Aplicações de Filas', 'Aplicações de Pilhas', 'Bom', 'Filas', 'Filas Dinâmicas', 'Filas Estáticas', 'Filas de Prioridade', 'Listas', 'Listas Dinâmicas', 'Listas Dinâmicas Duplamente Encadeadas', 'Listas Dinâmicas Duplamente Encadeadas Circulares', 'Listas Dinâmicas Simplesmente Encadeadas', 'Listas Dinâmicas Simplesmente Encadeadas Circulares', 'Listas Estáticas', 'Listas Estáticas Circulares', 'Listas Estáticas Encadeadas', 'Listas Estáticas Sequenciais', 'Percursos em Árvores Binárias', 'Pilhas', 'Pilhas Dinâmicas', 'Pilhas Estáticas', 'Péssimo', 'Recursividade', 'Regular', 'Ruim', 'Tipos Abstratos de Dados', 'Árvores BInárias de Busca Balanceadas', 'Árvores Binárias', 'Árvores Binárias de Busca', 'Ótimo']
30 itens distintos


In [7]:
# Creating a mapping from unique characters to indices

char2idx = {u:i for i, u in enumerate(vocab_l)}
idx2char = np.array(vocab_l)

text_as_int = np.array([char2idx[c] for c in data_set])

print('{')
for char,_ in zip(char2idx, range(100)):
    print('  {:4s}: {:3d},'.format(repr(char), char2idx[char]))

{
  'Aplicações de Filas':   0,
  'Aplicações de Pilhas':   1,
  'Bom':   2,
  'Filas':   3,
  'Filas Dinâmicas':   4,
  'Filas Estáticas':   5,
  'Filas de Prioridade':   6,
  'Listas':   7,
  'Listas Dinâmicas':   8,
  'Listas Dinâmicas Duplamente Encadeadas':   9,
  'Listas Dinâmicas Duplamente Encadeadas Circulares':  10,
  'Listas Dinâmicas Simplesmente Encadeadas':  11,
  'Listas Dinâmicas Simplesmente Encadeadas Circulares':  12,
  'Listas Estáticas':  13,
  'Listas Estáticas Circulares':  14,
  'Listas Estáticas Encadeadas':  15,
  'Listas Estáticas Sequenciais':  16,
  'Percursos em Árvores Binárias':  17,
  'Pilhas':  18,
  'Pilhas Dinâmicas':  19,
  'Pilhas Estáticas':  20,
  'Péssimo':  21,
  'Recursividade':  22,
  'Regular':  23,
  'Ruim':  24,
  'Tipos Abstratos de Dados':  25,
  'Árvores BInárias de Busca Balanceadas':  26,
  'Árvores Binárias':  27,
  'Árvores Binárias de Busca':  28,
  'Ótimo':  29,


In [8]:
#char2int das sequências

values = np.array(data_set)
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

['Listas Dinâmicas Simplesmente Encadeadas Circulares' 'Listas Estáticas'
 'Árvores Binárias' ... 'Filas de Prioridade' 'Pilhas Dinâmicas' 'Ótimo']
[12 13 27 ...  6 19 29]


In [9]:
#one-hot encoding das sequências

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [10]:
#reverter one-hot encoding das sequências

for i in onehot_encoded:
    inverted = label_encoder.inverse_transform([np.argmax(i)])
    print(inverted)

['Listas Dinâmicas Simplesmente Encadeadas Circulares']
['Listas Estáticas']
['Árvores Binárias']
['Listas Estáticas Circulares']
['Listas Estáticas Sequenciais']
['Listas Dinâmicas Duplamente Encadeadas']
['Filas de Prioridade']
['Pilhas']
['Listas Dinâmicas']
['Aplicações de Pilhas']
['Árvores Binárias de Busca']
['Pilhas Dinâmicas']
['Percursos em Árvores Binárias']
['Listas Dinâmicas Simplesmente Encadeadas']
['Árvores BInárias de Busca Balanceadas']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Filas Estáticas']
['Aplicações de Filas']
['Pilhas Estáticas']
['Tipos Abstratos de Dados']
['Listas Estáticas Encadeadas']
['Recursividade']
['Listas']
['Filas Dinâmicas']
['Filas']
['Ruim']
['Listas Estáticas Sequenciais']
['Filas Dinâmicas']
['Pilhas']
['Listas Estáticas Circulares']
['Filas Estáticas']
['Listas Dinâmicas Duplamente Encadeadas']
['Aplicações de Filas']
['Árvores Binárias']
['Listas Estáticas Encadeadas']
['Listas Estáticas']
['Listas']
['Pilhas Estáticas']
['Ti

['Aplicações de Pilhas']
['Listas Dinâmicas Simplesmente Encadeadas Circulares']
['Listas Estáticas Encadeadas']
['Listas Dinâmicas']
['Percursos em Árvores Binárias']
['Listas Dinâmicas Duplamente Encadeadas']
['Pilhas']
['Listas Dinâmicas Simplesmente Encadeadas']
['Recursividade']
['Filas Estáticas']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Regular']
['Listas Estáticas Encadeadas']
['Aplicações de Pilhas']
['Árvores BInárias de Busca Balanceadas']
['Pilhas Estáticas']
['Listas Estáticas']
['Listas Estáticas Circulares']
['Recursividade']
['Listas Estáticas Sequenciais']
['Pilhas Dinâmicas']
['Filas de Prioridade']
['Listas']
['Listas Dinâmicas']
['Aplicações de Filas']
['Filas Estáticas']
['Árvores Binárias de Busca']
['Tipos Abstratos de Dados']
['Filas Dinâmicas']
['Pilhas']
['Listas Dinâmicas Duplamente Encadeadas']
['Árvores Binárias']
['Percursos em Árvores Binárias']
['Listas Dinâmicas Simplesmente Encadeadas Circulares']
['Filas']
['Listas Dinâmicas Simplesment

['Pilhas Dinâmicas']
['Filas']
['Filas de Prioridade']
['Listas Estáticas Encadeadas']
['Listas Estáticas']
['Árvores Binárias de Busca']
['Listas Estáticas Circulares']
['Listas Dinâmicas']
['Listas Dinâmicas Duplamente Encadeadas']
['Listas Dinâmicas Simplesmente Encadeadas']
['Aplicações de Filas']
['Percursos em Árvores Binárias']
['Recursividade']
['Tipos Abstratos de Dados']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Listas Estáticas Sequenciais']
['Árvores Binárias']
['Filas Estáticas']
['Aplicações de Pilhas']
['Árvores BInárias de Busca Balanceadas']
['Filas Dinâmicas']
['Pilhas']
['Bom']
['Pilhas']
['Aplicações de Pilhas']
['Listas Dinâmicas Duplamente Encadeadas']
['Pilhas Dinâmicas']
['Pilhas Estáticas']
['Árvores Binárias']
['Listas Estáticas']
['Filas Dinâmicas']
['Listas Dinâmicas Simplesmente Encadeadas']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Listas Estáticas Circulares']
['Árvores Binárias de Busca']
['Árvores BInárias de Busca Balanceada

['Filas Dinâmicas']
['Percursos em Árvores Binárias']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Árvores Binárias']
['Bom']
['Recursividade']
['Filas Dinâmicas']
['Árvores Binárias de Busca']
['Listas Estáticas Encadeadas']
['Filas']
['Pilhas Dinâmicas']
['Filas Estáticas']
['Listas']
['Árvores BInárias de Busca Balanceadas']
['Árvores Binárias']
['Listas Dinâmicas']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Pilhas Estáticas']
['Listas Estáticas']
['Listas Estáticas Circulares']
['Pilhas']
['Aplicações de Filas']
['Listas Dinâmicas Simplesmente Encadeadas Circulares']
['Tipos Abstratos de Dados']
['Percursos em Árvores Binárias']
['Listas Estáticas Sequenciais']
['Filas de Prioridade']
['Listas Dinâmicas Simplesmente Encadeadas']
['Listas Dinâmicas Duplamente Encadeadas']
['Aplicações de Pilhas']
['Ótimo']
['Listas Estáticas Sequenciais']
['Listas']
['Filas']
['Árvores BInárias de Busca Balanceadas']
['Filas Estáticas']
['Listas Dinâmicas Simplesmente Encadea

['Filas Estáticas']
['Pilhas']
['Listas']
['Filas']
['Ótimo']
['Filas']
['Listas']
['Aplicações de Filas']
['Listas Dinâmicas Simplesmente Encadeadas Circulares']
['Recursividade']
['Listas Estáticas']
['Filas Dinâmicas']
['Filas Estáticas']
['Árvores Binárias de Busca']
['Listas Dinâmicas Simplesmente Encadeadas']
['Pilhas Dinâmicas']
['Tipos Abstratos de Dados']
['Listas Estáticas Encadeadas']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Listas Dinâmicas Duplamente Encadeadas']
['Pilhas Estáticas']
['Listas Estáticas Circulares']
['Percursos em Árvores Binárias']
['Aplicações de Pilhas']
['Listas Dinâmicas']
['Pilhas']
['Listas Estáticas Sequenciais']
['Árvores Binárias']
['Árvores BInárias de Busca Balanceadas']
['Filas de Prioridade']
['Regular']
['Listas Estáticas']
['Árvores Binárias de Busca']
['Recursividade']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Listas Dinâmicas Duplamente Encadeadas']
['Listas Dinâmicas']
['Listas Estáticas Sequenciais']
['Filas 

['Filas de Prioridade']
['Percursos em Árvores Binárias']
['Pilhas']
['Listas Estáticas Sequenciais']
['Listas Dinâmicas Simplesmente Encadeadas']
['Listas Dinâmicas']
['Pilhas Estáticas']
['Aplicações de Filas']
['Filas']
['Árvores Binárias de Busca']
['Pilhas Dinâmicas']
['Filas Dinâmicas']
['Recursividade']
['Listas Estáticas']
['Listas Dinâmicas Duplamente Encadeadas']
['Aplicações de Pilhas']
['Listas']
['Regular']
['Filas']
['Pilhas']
['Listas Dinâmicas Simplesmente Encadeadas']
['Aplicações de Filas']
['Pilhas Dinâmicas']
['Listas Estáticas Encadeadas']
['Listas Estáticas Circulares']
['Percursos em Árvores Binárias']
['Filas de Prioridade']
['Árvores Binárias']
['Filas Estáticas']
['Listas Estáticas Sequenciais']
['Aplicações de Pilhas']
['Árvores BInárias de Busca Balanceadas']
['Listas Dinâmicas Duplamente Encadeadas']
['Recursividade']
['Listas']
['Listas Dinâmicas']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Tipos Abstratos de Dados']
['Filas Dinâmicas']
['Pilh

['Listas Dinâmicas']
['Listas Dinâmicas Duplamente Encadeadas']
['Listas Estáticas Encadeadas']
['Árvores Binárias']
['Filas de Prioridade']
['Ótimo']
['Listas Estáticas']
['Filas de Prioridade']
['Listas Dinâmicas']
['Percursos em Árvores Binárias']
['Listas Dinâmicas Duplamente Encadeadas']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Listas Estáticas Circulares']
['Pilhas Dinâmicas']
['Listas Dinâmicas Simplesmente Encadeadas Circulares']
['Tipos Abstratos de Dados']
['Árvores Binárias']
['Pilhas']
['Árvores Binárias de Busca']
['Recursividade']
['Aplicações de Pilhas']
['Filas Dinâmicas']
['Listas Dinâmicas Simplesmente Encadeadas']
['Árvores BInárias de Busca Balanceadas']
['Listas Estáticas Sequenciais']
['Listas']
['Filas Estáticas']
['Aplicações de Filas']
['Pilhas Estáticas']
['Filas']
['Listas Estáticas Encadeadas']
['Regular']
['Listas Dinâmicas Duplamente Encadeadas']
['Listas Dinâmicas Simplesmente Encadeadas']
['Listas Dinâmicas Duplamente Encadeadas Circulares

['Regular']
['Filas Estáticas']
['Listas Dinâmicas']
['Listas Estáticas Encadeadas']
['Recursividade']
['Pilhas Dinâmicas']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Listas Estáticas Circulares']
['Pilhas']
['Pilhas Estáticas']
['Listas Dinâmicas Duplamente Encadeadas']
['Aplicações de Pilhas']
['Árvores BInárias de Busca Balanceadas']
['Árvores Binárias']
['Listas Estáticas']
['Aplicações de Filas']
['Listas Dinâmicas Simplesmente Encadeadas']
['Árvores Binárias de Busca']
['Filas de Prioridade']
['Listas Dinâmicas Simplesmente Encadeadas Circulares']
['Percursos em Árvores Binárias']
['Tipos Abstratos de Dados']
['Filas Dinâmicas']
['Listas Estáticas Sequenciais']
['Filas']
['Listas']
['Ótimo']
['Pilhas Dinâmicas']
['Árvores BInárias de Busca Balanceadas']
['Listas']
['Listas Dinâmicas Simplesmente Encadeadas Circulares']
['Aplicações de Filas']
['Listas Estáticas Circulares']
['Recursividade']
['Listas Dinâmicas Duplamente Encadeadas Circulares']
['Aplicações de Pilhas

In [11]:
##### Create training examples and targets #####

# The maximum length sentence we want for a single input in characters
seq_length = 25
examples_per_epoch = len(data_set)#(seq_length+1)

char_dataset = tf.data.Dataset.from_tensor_slices(onehot_encoded)
# for i in char_dataset:
#     print(i)

sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

#print batches encoded
for i in sequences:
    print(i)
    
#print batches as text
for i in sequences:
    for j in i:
        print(''.join(label_encoder.inverse_transform([np.argmax(j)])))

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

  1. 0. 0. 0. 0. 0.]], shape=(26, 30), dtype=float64)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0

  0. 0. 0. 0. 0. 1.]], shape=(26, 30), dtype=float64)
tf.Tensor(
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0

  0. 0. 0. 0. 0. 0.]], shape=(26, 30), dtype=float64)
tf.Tensor(
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0

  0. 0. 0. 0. 0. 1.]], shape=(26, 30), dtype=float64)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0

  0. 0. 0. 0. 0. 1.]], shape=(26, 30), dtype=float64)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

Filas
Péssimo
Tipos Abstratos de Dados
Recursividade
Listas Dinâmicas Simplesmente Encadeadas
Árvores Binárias
Filas Estáticas
Filas de Prioridade
Listas
Árvores BInárias de Busca Balanceadas
Pilhas
Pilhas Estáticas
Árvores Binárias de Busca
Listas Estáticas Sequenciais
Listas Estáticas Encadeadas
Listas Estáticas
Pilhas Dinâmicas
Aplicações de Pilhas
Listas Dinâmicas
Aplicações de Filas
Listas Dinâmicas Duplamente Encadeadas
Listas Estáticas Circulares
Filas
Percursos em Árvores Binárias
Listas Dinâmicas Duplamente Encadeadas Circulares
Listas Dinâmicas Simplesmente Encadeadas Circulares
Filas Dinâmicas
Péssimo
Listas Estáticas Sequenciais
Filas de Prioridade
Árvores Binárias de Busca
Aplicações de Filas
Filas
Listas Estáticas
Listas Estáticas Encadeadas
Pilhas Estáticas
Percursos em Árvores Binárias
Filas Dinâmicas
Pilhas
Listas Estáticas Circulares
Recursividade
Listas Dinâmicas Duplamente Encadeadas Circulares
Árvores BInárias de Busca Balanceadas
Árvores Binárias
Pilhas Dinâmicas


Listas Dinâmicas Simplesmente Encadeadas Circulares
Árvores Binárias de Busca
Ruim
Listas Estáticas Sequenciais
Listas Estáticas
Pilhas Dinâmicas
Listas Estáticas Encadeadas
Listas
Pilhas
Aplicações de Filas
Árvores Binárias
Pilhas Estáticas
Recursividade
Filas de Prioridade
Árvores Binárias de Busca
Listas Estáticas Circulares
Percursos em Árvores Binárias
Listas Dinâmicas Duplamente Encadeadas
Listas Dinâmicas Simplesmente Encadeadas Circulares
Tipos Abstratos de Dados
Filas Dinâmicas
Árvores BInárias de Busca Balanceadas
Listas Dinâmicas
Listas Dinâmicas Duplamente Encadeadas Circulares
Filas Estáticas
Listas Dinâmicas Simplesmente Encadeadas
Aplicações de Pilhas
Filas
Ótimo
Listas Dinâmicas Duplamente Encadeadas
Listas Dinâmicas
Filas Estáticas
Listas
Aplicações de Filas
Listas Dinâmicas Simplesmente Encadeadas
Tipos Abstratos de Dados
Filas
Árvores Binárias de Busca
Listas Estáticas Circulares
Filas Dinâmicas
Filas de Prioridade
Listas Estáticas Encadeadas
Listas Estáticas Sequenc

Listas Estáticas Sequenciais
Listas Dinâmicas Duplamente Encadeadas Circulares
Aplicações de Filas
Pilhas Estáticas
Listas Estáticas
Pilhas
Listas
Ruim
Aplicações de Filas
Aplicações de Pilhas
Listas Estáticas Circulares
Listas Estáticas Sequenciais
Filas Dinâmicas
Pilhas
Listas Dinâmicas Duplamente Encadeadas Circulares
Árvores BInárias de Busca Balanceadas
Árvores Binárias de Busca
Listas
Filas de Prioridade
Recursividade
Filas Estáticas
Filas
Pilhas Dinâmicas
Árvores Binárias
Listas Estáticas Encadeadas
Tipos Abstratos de Dados
Percursos em Árvores Binárias
Listas Dinâmicas Simplesmente Encadeadas Circulares
Listas Estáticas
Listas Dinâmicas Simplesmente Encadeadas
Listas Dinâmicas Duplamente Encadeadas
Pilhas Estáticas
Listas Dinâmicas
Regular
Aplicações de Filas
Listas Estáticas Circulares
Listas Dinâmicas Duplamente Encadeadas
Listas Dinâmicas
Listas Dinâmicas Simplesmente Encadeadas Circulares
Listas Dinâmicas Duplamente Encadeadas Circulares
Pilhas Estáticas
Tipos Abstratos de 

Árvores Binárias de Busca
Filas Estáticas
Pilhas Estáticas
Listas Dinâmicas Simplesmente Encadeadas
Árvores Binárias
Pilhas
Aplicações de Filas
Percursos em Árvores Binárias
Pilhas Dinâmicas
Árvores BInárias de Busca Balanceadas
Filas Dinâmicas
Listas Estáticas Sequenciais
Listas Dinâmicas Simplesmente Encadeadas Circulares
Filas
Ruim
Listas Dinâmicas Duplamente Encadeadas
Árvores Binárias
Filas Estáticas
Listas Dinâmicas Duplamente Encadeadas Circulares
Listas Dinâmicas Simplesmente Encadeadas
Tipos Abstratos de Dados
Pilhas
Listas
Listas Estáticas
Pilhas Estáticas
Pilhas Dinâmicas
Listas Estáticas Encadeadas
Listas Dinâmicas
Listas Estáticas Circulares
Listas Dinâmicas Simplesmente Encadeadas Circulares
Árvores Binárias de Busca
Filas
Filas de Prioridade
Recursividade
Aplicações de Pilhas
Árvores BInárias de Busca Balanceadas
Filas Dinâmicas
Listas Estáticas Sequenciais
Percursos em Árvores Binárias
Aplicações de Filas
Ótimo
Aplicações de Filas
Tipos Abstratos de Dados
Listas Estátic

Listas
Listas Dinâmicas
Tipos Abstratos de Dados
Árvores Binárias
Árvores Binárias de Busca
Listas Dinâmicas Duplamente Encadeadas
Listas Estáticas Encadeadas
Pilhas
Listas Dinâmicas Duplamente Encadeadas Circulares
Aplicações de Filas
Listas Estáticas Circulares
Listas Estáticas Sequenciais
Listas Dinâmicas Simplesmente Encadeadas Circulares
Filas de Prioridade
Listas Estáticas
Filas
Péssimo
Filas de Prioridade
Listas Dinâmicas Duplamente Encadeadas Circulares
Árvores Binárias de Busca
Pilhas
Listas Dinâmicas Simplesmente Encadeadas Circulares
Árvores BInárias de Busca Balanceadas
Aplicações de Filas
Filas Dinâmicas
Recursividade
Pilhas Estáticas
Percursos em Árvores Binárias
Pilhas Dinâmicas
Filas
Listas Estáticas Encadeadas
Listas Dinâmicas Duplamente Encadeadas
Listas Estáticas Circulares
Tipos Abstratos de Dados
Listas Dinâmicas Simplesmente Encadeadas
Listas Estáticas Sequenciais
Filas Estáticas
Listas Dinâmicas
Listas Estáticas
Árvores Binárias
Listas
Aplicações de Pilhas
Péssim

In [12]:
##### Create training examples and targets #####

def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

#foreach item in sequences apply split_input_target
dataset = sequences.map(split_input_target)

#print input_text and target_text as text
#não necessário, para visualização
for input_example, target_example in dataset.take(1):
    print('-----Input-----')
    for i in input_example:
        print(''.join(label_encoder.inverse_transform([np.argmax(i)])))
    print('-----Target-----')
    for i in target_example:
        print(''.join(label_encoder.inverse_transform([np.argmax(i)])))

-----Input-----
Listas Dinâmicas Simplesmente Encadeadas Circulares
Listas Estáticas
Árvores Binárias
Listas Estáticas Circulares
Listas Estáticas Sequenciais
Listas Dinâmicas Duplamente Encadeadas
Filas de Prioridade
Pilhas
Listas Dinâmicas
Aplicações de Pilhas
Árvores Binárias de Busca
Pilhas Dinâmicas
Percursos em Árvores Binárias
Listas Dinâmicas Simplesmente Encadeadas
Árvores BInárias de Busca Balanceadas
Listas Dinâmicas Duplamente Encadeadas Circulares
Filas Estáticas
Aplicações de Filas
Pilhas Estáticas
Tipos Abstratos de Dados
Listas Estáticas Encadeadas
Recursividade
Listas
Filas Dinâmicas
Filas
-----Target-----
Listas Estáticas
Árvores Binárias
Listas Estáticas Circulares
Listas Estáticas Sequenciais
Listas Dinâmicas Duplamente Encadeadas
Filas de Prioridade
Pilhas
Listas Dinâmicas
Aplicações de Pilhas
Árvores Binárias de Busca
Pilhas Dinâmicas
Percursos em Árvores Binárias
Listas Dinâmicas Simplesmente Encadeadas
Árvores BInárias de Busca Balanceadas
Listas Dinâmicas Dupla

In [13]:
#não necessário, para visualização
for input_example, target_example in dataset.take(1):
    for i, (input_idx, target_idx) in enumerate(zip(input_example, target_example)):
        print("Step {:4d}".format(i))
        print("  input: {} ({:s})".format(input_idx, str(label_encoder.inverse_transform([np.argmax(input_idx)]))))
        print("  expected output: {} ({:s})".format(target_idx, str(label_encoder.inverse_transform([np.argmax(target_idx)]))))
    print('------------------------------------------------------------------')

Step    0
  input: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.] (['Listas Dinâmicas Simplesmente Encadeadas Circulares'])
  expected output: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.] (['Listas Estáticas'])
Step    1
  input: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.] (['Listas Estáticas'])
  expected output: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0.] (['Árvores Binárias'])
Step    2
  input: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0.] (['Árvores Binárias'])
  expected output: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.] (['Listas Estáticas Circulares'])
Step    3
  input: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.] (['Listas Estáticas Circulares']

In [15]:
##### Create training batches #####

# Batch size
BATCH_SIZE = 1

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 50

# print(dataset)
# for i in dataset:
#     print(i)

datasetBatch = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)
# If your program depends on the batches having the same outer dimension,
# you should set the drop_remainder argument to True to prevent the smaller
# batch from being produced.

print(datasetBatch)
for i in datasetBatch.take(1):
    print(i)


#for i in datasetBatch.take(1):
#    for j in i:
#        for a in j:
#            for e in a:
#                print(''.join(label_encoder.inverse_transform([np.argmax(e)])))

<BatchDataset shapes: ((1, 25, 30), (1, 25, 30)), types: (tf.float64, tf.float64)>
(<tf.Tensor: shape=(1, 25, 30), dtype=float64, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 

In [93]:
##### Building the model #####

# Length of the vocabulary in chars
vocab_size = len(vocab_l)

# Number of RNN units
rnn_units = 1024

def build_model(vocab_size, rnn_units):
    model = tf.keras.Sequential([
        tf.keras.layers.LSTM(rnn_units,batch_input_shape=(1, 25, 30),
                        return_sequences=True,
                        stateful=True,
                        recurrent_initializer='glorot_uniform'),
        tf.keras.layers.Dense(vocab_size)
    ])
    return model

model = build_model(
    vocab_size = len(vocab_l),
    rnn_units=rnn_units)

In [94]:
 model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_8 (LSTM)                (1, 25, 1024)             4321280   
_________________________________________________________________
dense_10 (Dense)             (1, 25, 30)               30750     
Total params: 4,352,030
Trainable params: 4,352,030
Non-trainable params: 0
_________________________________________________________________


In [95]:
##### Testing the model #####

for input_example_batch, target_example_batch in datasetBatch.take(1):
    print('Input:',input_example_batch)
    print()
    
    print('Target:',target_example_batch)
    print()
    
    example_batch_predictions = model(input_example_batch)
    print('Batche Predictions:',example_batch_predictions, "# (batch_size, sequence_length, vocab_size)")
 

Input: tf.Tensor(
[[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
   0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 

In [96]:
##### Try prediction for the first example in the batch #####
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
print(sampled_indices)
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()
print(sampled_indices)

tf.Tensor(
[[23]
 [27]
 [14]
 [ 4]
 [13]
 [25]
 [16]
 [ 4]
 [23]
 [14]
 [29]
 [ 6]
 [20]
 [24]
 [19]
 [ 3]
 [ 3]
 [13]
 [22]
 [ 2]
 [ 7]
 [ 9]
 [ 1]
 [15]
 [ 7]], shape=(25, 1), dtype=int64)
[23 27 14  4 13 25 16  4 23 14 29  6 20 24 19  3  3 13 22  2  7  9  1 15
  7]


# Training the model

In [97]:
##### Attach an optimizer, and a loss function #####

loss = tf.keras.losses.BinaryCrossentropy(from_logits=True)
print(loss(target_example_batch, example_batch_predictions).numpy())
model.compile(optimizer='adam', loss=loss)

0.6929062


In [98]:
##### Configure checkpoints #####

# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

In [99]:
##### Execute the training #####

EPOCHS=50
history = model.fit(datasetBatch, epochs=EPOCHS, callbacks=[checkpoint_callback])

Epoch 1/50
100/100 [==============================] - 30s 304ms/step - loss: 0.1630
Epoch 2/50
100/100 [==============================] - 31s 305ms/step - loss: 0.1440
Epoch 3/50
100/100 [==============================] - 34s 343ms/step - loss: 0.1436
Epoch 4/50
100/100 [==============================] - 31s 305ms/step - loss: 0.1433
Epoch 5/50
100/100 [==============================] - 31s 311ms/step - loss: 0.1432
Epoch 6/50
100/100 [==============================] - 30s 302ms/step - loss: 0.1427
Epoch 7/50
100/100 [==============================] - 31s 307ms/step - loss: 0.1425
Epoch 8/50
100/100 [==============================] - 30s 301ms/step - loss: 0.1420
Epoch 9/50
100/100 [==============================] - 30s 305ms/step - loss: 0.1416
Epoch 10/50
100/100 [==============================] - 31s 305ms/step - loss: 0.1409
Epoch 11/50
100/100 [==============================] - 30s 299ms/step - loss: 0.1400
Epoch 12/50
100/100 [==============================] - 30s 301ms/step - lo

# Generate text

In [100]:
##### Restore the latest checkpoint #####

#print(tf.train.latest_checkpoint(checkpoint_dir))
model = build_model(vocab_size, rnn_units)
model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))
model.build(tf.TensorShape([1, None]))
#model.summary()

In [101]:
def generate_seq(model, start_string):
    
    # Find encoded value of start_string
    label_encoder = LabelEncoder()
    integer_encoded = label_encoder.fit_transform(vocab_l)
    onehot_encoder = OneHotEncoder(sparse=False)
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    index = vocab_l.index(start_string)
    
    # Set shape to (1,1,30)
    conteudo_input = onehot_encoded[index]
    conteudo_input = tf.expand_dims(conteudo_input, 0)
    conteudo_input = tf.expand_dims(conteudo_input, 1)
    
    # Number of characters to generate
    num_generate = 25
    
    # Empty string to store our results
    text_generated = [start_string]
    
    # Low temperatures results in more predictable text.
    # Higher temperatures results in more surprising text.
    # Experiment to find the best setting.
    temperature = 1.0
    model.reset_states()
    for i in range(num_generate):
        predictions = model(conteudo_input) #here
        # remove the batch dimension
        predictions = tf.squeeze(predictions, 0)
        # using a categorical distribution to predict the character returned by the model
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
        # We pass the predicted character as the next input to the model
        # along with the previous hidden state
        conteudo_input = tf.expand_dims(onehot_encoded[predicted_id], 0)
        conteudo_input = tf.expand_dims(conteudo_input, 1)
        text_generated.append(vocab_l[predicted_id])
    return text_generated

In [102]:
print(generate_seq(model, start_string='Pilhas'))

['Pilhas', 'Listas Estáticas', 'Listas Estáticas Sequenciais', 'Pilhas Estáticas', 'Listas Dinâmicas', 'Filas Dinâmicas', 'Filas de Prioridade', 'Listas Estáticas Circulares', 'Aplicações de Pilhas', 'Listas Estáticas Encadeadas', 'Percursos em Árvores Binárias', 'Listas Dinâmicas Simplesmente Encadeadas Circulares', 'Pilhas', 'Listas Estáticas Sequenciais', 'Tipos Abstratos de Dados', 'Listas Dinâmicas Simplesmente Encadeadas Circulares', 'Regular', 'Filas Dinâmicas', 'Árvores Binárias', 'Listas Dinâmicas Simplesmente Encadeadas', 'Árvores BInárias de Busca Balanceadas', 'Tipos Abstratos de Dados', 'Percursos em Árvores Binárias', 'Árvores Binárias de Busca', 'Árvores Binárias', 'Listas Dinâmicas Duplamente Encadeadas Circulares']


# Teste

In [103]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [104]:
inputs = tf.random.normal([1, 25, 8])
print(inputs)
lstm = tf.keras.layers.LSTM(1024)
output = lstm(inputs)
#print(output.shape)
#print(output)

tf.Tensor(
[[[-0.21787201  0.15361904 -1.0107477  -0.31228146 -0.26803914
   -0.7015582  -2.0886137  -0.51794016]
  [-1.4166747   0.1352451   2.8171425  -1.859746   -0.82068896
   -0.04070163  1.8144675  -0.4787139 ]
  [ 0.90056825 -0.6609909   0.2588832  -0.71794224  1.5942265
   -0.2913395   0.603835   -0.03111868]
  [ 3.0846279  -0.41715926  0.06117619  0.820209   -1.2320846
    0.4933971  -0.6383907   0.36975253]
  [-0.33095944 -0.29030296  2.7654507   0.02223049  0.94616127
   -1.0504653   1.2049488   0.1541086 ]
  [-0.71387756  0.627334    1.0207108   2.1412485  -0.27715403
   -0.87144136 -0.5279307  -0.01802154]
  [ 0.92600954 -0.42792207  0.8273307  -1.3924971  -0.63654006
   -0.12605512 -2.7368617   0.24865095]
  [ 0.08350786 -0.84679574  1.1138921   1.1924255   0.3557175
    1.8539625   0.7297549  -1.5025635 ]
  [-0.88245255  0.84470606  0.0964893  -0.5835058  -1.7736198
   -2.2414565  -0.27078885  0.38677782]
  [-1.7754105   1.408366   -0.54418576 -1.886459   -0.7040793
   -

In [105]:
inputs = tf.random.normal([32, 10, 8])
dense = tf.keras.layers.Dense(36)
output = dense(inputs)
print(output.shape)
print(output)

(32, 10, 36)
tf.Tensor(
[[[ 5.38578928e-01  7.52727747e-01  4.83285844e-01 ...  1.13003865e-01
   -2.67841339e-01 -7.91590691e-01]
  [-5.43794036e-03  4.51729417e-01 -6.26727462e-01 ... -1.35367143e+00
   -2.72160530e-01 -8.85064542e-01]
  [-1.22659779e+00  6.80881217e-02  8.08683097e-01 ... -1.43420279e-01
    5.78792572e-01  5.78712106e-01]
  ...
  [-4.01067585e-01  1.65700287e-01  2.20171720e-01 ... -4.50489447e-02
    8.05609465e-01 -2.23395109e-01]
  [-6.49823368e-01  2.88545638e-02  8.58930647e-01 ... -2.47058898e-01
    7.38778412e-01  1.94298714e-01]
  [-5.25550663e-01  7.10413933e-01  1.04225254e+00 ...  5.71628511e-01
    2.68167466e-01  3.97111982e-01]]

 [[-1.44879627e+00 -4.48347300e-01  8.42741430e-02 ... -8.89450461e-02
    1.41017854e+00  3.94003272e-01]
  [ 1.43029630e-01  1.32733607e+00  3.01563352e-01 ... -1.03353429e+00
    4.78304327e-02 -7.61996865e-01]
  [-1.19253755e-01  6.09515607e-02 -2.21118301e-01 ... -7.77918994e-02
    9.70446587e-01 -3.99824172e-01]
  ...

In [106]:
# Create a `Sequential` model and add a Dense layer as the first layer.
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(1,25,1024)))
model.add(tf.keras.layers.Dense(36, activation='relu'))
# Now the model will take as input arrays of shape (None, 16)
# and output arrays of shape (None, 32).
# Note that after the first layer, you don't need to specify
# the size of the input anymore:
model.add(tf.keras.layers.Dense(36))
print(model.output_shape)
print(model)

(None, 1, 25, 36)
